add_diff_step: 0
burnin: 0
constraint: Mol-Weight-Box
max_samples: 10000
method:
  gamma: 1.0
  op: proj
  solve_order: cpj
  jacobian: false
  density_lambda: 0.0
  last_score: false
params:
- - 12.0106
  - 14.006855
  - 15.9994
  - 18.998403163
- - 24.02
  - 137.04

rounding: none
schedule:
  gamma: exp-dist
  params:
  - 0
  - 10000
implicit: false
eq: false
