data:
  data: grid
  dir: './data'
  test_split: 0.2
  adj_vals: [0, 1]
  feat_vals: []

ckpt: gdss_grid

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.1
  scale_eps: 0.7
  n_steps: 1

sample:
  use_ema: True
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 13
