data:
  data: community_small
  dir: './data'
  adj_vals: [0, 1]
  feat_vals: []

ckpt: gdss_community_small

sampler:
  predictor: Euler
  corrector: Langevin
  snr: 0.05
  scale_eps: 0.7
  n_steps: 10 #corrector steps

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 11
