data:
  data: ego_small
  dir: './data'
  adj_vals: [0, 1]
  feat_vals: []

ckpt: gdss_ego_small

sampler:
  predictor: Euler
  corrector: None
  snr: 0.0
  scale_eps: 0.0
  n_steps: 1

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 12
