data:
  data: sbm
  dir: './data'
  test_split: 0.2
  adj_vals: [0, 1]
  feat_vals: []

ckpt: gdss_sbm

sampler:
  predictor: Euler
  corrector: Langevin
  snr: 0.05
  scale_eps: 1.0
  n_steps: 1 #corrector steps

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 11
