add_diff_step: 0
burnin: 0
constraint: Num-Edges
max_samples: 10000
method:
  gamma: 1.0
  op: proj
  solve_order: cpj
  jacobian: false
  density_lambda: 0.0
  last_score: false
params:
- zeros
- 972.0
rounding: none
schedule:
  gamma: poly
  params:
  - 0
  - 5
implicit: false
eq: false
