add_diff_step: 0
burnin: 0
constraint: Valency
max_samples: 10000
method:
  gamma: 1.0
  op: proj
  solve_order: cpj
params:
- - 4
  - 3
  - 2
  - 1
  - 5
  - 2
  - 1
  - 1
  - 1
rounding: none
schedule:
  gamma: poly
  params:
  - 0.1
  - 5
implicit: false
eq: false
