
# the output files will be stored in the directory <exp_dir>/<exp_name>
exp_dir: exp
exp_name: zinc

seed: 42

# where to find the saved models (you need to edit the path)
model_save_dir: 'exp/zinc/edp-gnn_ZINC250k__May-14-11-07-53_1043155/models'


# uncomment it to save the output files to `save_dir` instead of creating a new directory
save_dir: 'exp/zinc'

dataset:
  dataset_size: 0  # the maximal loaded dataset size
  max_node_num: 38
  max_feat_num: 9
  name: ZINC250k  # name of the dataset, the pickle file should be data/<name>.pkl

mcmc:  # hyper parameters in the Langevin MC sampling
  eps:
  - 0.5
  fixed_node_number: true
  grad_step_size:
  - 0.001
  # - 0.005
  name: langevin
  step_num: 1000
  
model:
  name: edp-gnn  # the name of the score-network, should be one of ['gnn', 'mlp', 'cov', 'unet', 'edp-gnn']
  models:
    model_1:
      dropout_p: 0.0
      gnn_hidden_num_list:  # feature number for each EDP-GNN layer
      - 16
      - 16
      - 16
      - 16
      feature_nums:  # F_i
      - 16
      - 16
      - 16
      - 16
      - 16
      channel_num_list:  # C_i
      - 2
      - 4
      - 4
      - 4
      - 2
      name: gin  # the name of the GNN, should be one of ['gin', 'gcn']
      use_norm_layers: false
  stack_num: 1

sample:
  batch_size: 10000

test:
  batch_size: 64

train:
  batch_size: 64

  lr_dacey: 0.999
  lr_init: 0.001
  momentum: 0.9

  max_epoch: 300
  sample_interval: 10000  # run sampling after <sample_interval> epochs
  save_interval: 300 # save the model after <save_interval> epochs

  shuffle: true
  sigmas:
  - 0.1
  - 0.2
  - 0.4
  - 0.6
  - 0.8
  - 1.6

  weight_decay: 0.0
