add_diff_step: 0
burnin: 0
constraint: Cheeger-bound
max_samples: 10000
method:
  gamma: 1.0
  op: proj
  solve_order: cpj
params:
- 0.36
- 4.0
rounding: none
schedule:
  gamma: poly
  params:
  - 0.1
  - 5
