community_small:
  bound: [1, 3, 5, 7, 10, 15]
grid:
  bound: [0.5, 1, 1.5, 2, 2.5, 5, 10]
ego_small:
  bound: [0.5, 1, 1.5, 2, 2.5, 5, 10]
enzymes:
  bound: [0.5, 1, 1.5, 2, 2.5, 5, 10]
qm9:
  bound: [0.5, 1, 1.5, 2, 2.5, 5, 10]
zinc250k:
  bound: [0.5, 1, 1.5, 2, 2.5, 5, 10]
