add_diff_step: 0
burnin: 0
constraint: Nconn_atleast
max_samples: 10000
method:
  gamma: 1.0
  op: proj
  solve_order: cpj
params:
- 106
rounding: none
schedule:
  gamma: poly
  params:
  - 0.1
  - 5
