add_diff_step: 0
burnin: 0
constraint: Max-Degree-Box
max_samples: 10000
method:
  gamma: 1.0
  op: proj
  solve_order: cpj
  jacobian: false
  density_lambda: 0.0
  last_score: true
params:
- 2.0
- 11.0
rounding: none
schedule:
  gamma: poly
  params:
  - 0.1
  - 5
implicit: false
eq: false
